# reviewdog.yml

runner:
    cmd: golangci-lint run --out-format=line-number ./... -E golint -E goimports -E misspell -E unparam
    errorformat:
      - '%E%f:%l:%c: %m'
      - '%E%f:%l: %m'
      - '%C%.%#'
